### ISSUE TITLE
plugin binary can't find elasticsearch defaults file on Ubuntu 14.04

### ISSUE THREAD

**Issue by philipwigg** [elastic/ansible-elasticsearch#110]
I am using Ubuntu 14.04.

I am configuring Elasticsearch in a role like so:-

```
    - { role: elasticsearch,
              es_instance_name: "es01",
              es_heap_size: "3g",
              es_data_dirs: "/opt/app/elasticsearch/data",
              es_log_dir: "/opt/app/elasticsearch/logs",
              es_work_dir: "/opt/app/elasticsearch/temp",
              es_config: { network.host: '[ "_local_", "_docker0_" ]',
                           transport.host: '_eth0_',
                           http.port: 9200,
                           transport.tcp.port: 9300,
                           max-open-files: true,
                           bootstrap.mlockall: true,
                           script.inline: true,
                           script.indexed: true,
                           index.translog.durability: async,
                           index.queries.cache.everything: true } }
```

This leaves me with a defaults file at ```/etc/default/es01_elasticsearch```.

This happens when I try to run the ```plugin``` command:-
```
root@my-es-host:/usr/share/elasticsearch# bin/plugin                                               │~
bin/plugin: 49: .: Can't open //etc/default/elasticsearch
```

I can fix it up manually by editing ```bin/plugin``` like so:-

```
ES_ENV_FILE="/etc/default/es01_elasticsearch"
```

Am I missing some configuration or is this a bug? Thanks for your help.

**Comment by jakommo** [comment]
Hi @philipwigg, sorry for the delay and thanks for opening this issue.

Is there a reason you are manually installing the plugin instead of using something like the following in the playbook?

```
  vars:
    es_plugins:
        - plugin: license
```

I don't consider this a bug as `/usr/share/elasticsearch` will be used for all the nodes, in a multiple nodes per host setup and thus it's not possible to edit the `bin/plugin` script itself. 
Also the role does allow installing plugins, which cover this ENV setting already. 

Closing for now. Feel free to reopen if you disagree and want to discuss this further.
