### ISSUE TITLE
ERROR: plugin directory already exists (idempotence)

### ISSUE THREAD

**Issue by marji** [elastic/ansible-elasticsearch#111]
**Issue:** The plugin management is not idempotent (using current master, commit [e14ebe0](https://github.com/elastic/ansible-elasticsearch/tree/e14ebe06ab68d8daf19f86f55e600b5249a4a9d8)).

A plugin gets installed on first ansible-playbook run and causes "ERROR: plugin directory already exists" on the second run.

To be able to run a playbook multiple time, one has to workaround it by setting _es_plugins_reinstall_ to true (default is false), but then the playbook reports changes on each run (not idempotent either).

**Expected behaviour:** second run finishes without error, with zero changes.

**Environment:** Fresh Ubuntu 14.04 64bit in Vagrant

**Playbook (idemp.yml):**

``` YAML

---
- name: Provision the ES node or cluster
  hosts: es
  remote_user: vagrant
  become: yes
  become_user: root
  gather_facts: true

  vars:
    es_plugins:
      - plugin: cloud-aws

  roles:
    - { role: elasticsearch, es_instance_name: "node1" }
```

**First run:**

```
marji@anna:~/projects/ansible-project-logstash$ ansible-playbook -i hosts idemp.yml 

--- cut ---

PLAY RECAP *********************************************************************
10.8.8.2                   : ok=47   changed=18   unreachable=0    failed=0   
```

**Second run:**

```
marji@anna:~/projects/ansible-project-logstash$ ansible-playbook -i hosts idemp.yml 

--- cut ---

TASK [elasticsearch : Remove elasticsearch plugins] ****************************
skipping: [10.8.8.2] => (item= cloud-aws) 

TASK [elasticsearch : Install elasticsearch plugins] ***************************
failed: [10.8.8.2] => (item={u'plugin': u'cloud-aws'}) => {"changed": false, "cmd": ["/usr/share/elasticsearch/bin/plugin", "install", "cloud-aws", "--silent"], "delta": "0:00:10.256230", "end": "2016-06-05 03:27:35.476620", "failed": true, "failed_when_result": true, "item": {"plugin": "cloud-aws"}, "rc": 74, "start": "2016-06-05 03:27:25.220390", "stderr": "", "stdout": "ERROR: plugin directory /usr/share/elasticsearch/plugins/node1/cloud-aws already exists. To update the plugin, uninstall it first using 'remove cloud-aws' command", "stdout_lines": ["ERROR: plugin directory /usr/share/elasticsearch/plugins/node1/cloud-aws already exists. To update the plugin, uninstall it first using 'remove cloud-aws' command"], "warnings": []}

PLAY RECAP *********************************************************************
10.8.8.2                   : ok=43   changed=0    unreachable=0    failed=1   
```

**The error above is:** "ERROR: plugin directory /usr/share/elasticsearch/plugins/node1/cloud-aws already exists. To update the plugin, uninstall it first using 'remove cloud-aws' command"

**Comment by jakommo** [comment]
Thanks for reporting @marji . As a temporary workaround, at least for elastic provided plugins, you can set `es_plugins_reinstall: true`, which will cause a reinstall of all plugins on the second run.
The issue is caused by the role currently not checking which plugins are already installed.

@gingerwizard I think you already looked into a solution to something like this. Any ideaas?

**Comment by barryib** [comment]
So far my workaround for this issue is to explicitly tell the task to don't fail when plugins exist. See the PR #113 .

The great way would be to don't try to re-install plugins if they exist without an `es_plugins_reinstall: true`, but I went into plugins names issue. Where some plugins have a different name (short one) when they are installed. Ex: **mobz/elasticsearch-head** become **head** when installed

**Comment by gingerwizard** [comment]
@barryib agreed lets use the plugin module.

**Comment by barryib** [comment]
Can be addressed with #125

**Comment by martinb3** [comment]
@barryib Since Elasticsearch itself can't idempotently install plugins, I'm not sure how a different module for Ansible would solve the problem. From the docs to the module you linked:

> version  no 	None
> Version of the plugin to be installed. If plugin exists with previous version, it will NOT be updated

That to me sounds like not idempotent either, if giving a version and it won't actually be installed in every case.

For what it's worth, we have the same problem in the Chef cookbook for Elasticseach. :/

**Comment by barryib** [comment]
@martinb3 I think that the term "idempotency" is misleading us. We don't want to **install idempotently plugins** (as you mentioned it, Elasticsearch can't do that), but we wanted to run **idempotently our ansible tasks**.

Indeed, we can do that with a lot of "hacking" (by using shell, conditions, loop, etc.) or we can do it properly in an ansible style (with module already included since ansible 2.0).

For the point you're referring to:

> version no None
> Version of the plugin to be installed. If plugin exists with previous version, it will NOT be updated

Yes, right now the module wont update, but it wont break anything and can be run as many time you want (that is idempotency for ansible task)

Furthermore, I've submitted this [PR](https://github.com/ansible/ansible-modules-extras/pull/2604) to let user decided if he wanted to force install a plugin.

**Comment by martinb3** [comment]
Thank you for clarifying that -- I guess if the module doesn't do anything, it would technically be idempotent. Usually I think of idempotency in configuration management as "run it as many times as you want, and it will always bring the system into the same state, or do nothing if the system is already in the desired state." Anyway, yeah -- I wish we could do more with Elasticsearch's plugin system :)

**Comment by gingerwizard** [comment]
I'll tested this a while back and i believe its resolved.  It should be tested under https://github.com/elastic/ansible-elasticsearch/issues/43 which i will try to include shortly.
