### ISSUE TITLE
playbook does not install plugins

### ISSUE THREAD

**Issue by Thermi** [elastic/ansible-elasticsearch#163]
I'm trying to run a playbook on 4 EC2 instances, but the playbook does not install any plugins. Also, `/etc/sysconfig/elasticsearch` is missing.

The playbook is visible on [gist.github.com].(https://gist.github.com/Thermi/e74fb654d74d40f8f225ae81c2baac91)

`/etc/sysconfig/eleasticsearch` should be provided by the elasticsearch package, but it's not there.
It is required by `/usr/share/elasticsearch/bin/plugin`, which is a shell script and includes that file with `.`.
The EC2 instances run CentOS 7.

**Comment by jakommo** [comment]
Hi @Thermi,

the sysconfig file is not missing, it just uses another name when installed via this role (because you could setup multiple nodes per machine, thus different filenames are required.).
In case of your playbook it should be `/etc/sysconfig/cluster-master-1_elasticsearch` etc.

About the plugins, you didn't specify a elasticsearch version, so the latest will be used (currently `2.4.1`).
For ES `2.x`, the plugin naming scheme changed and the ones you use are for ES `1.x` .

For 2.x you need the use the following:

```
    es_plugins:
     - plugin: license
     - plugin: cloud-aws
```

Questions:

* When you got the error about `/etc/sysconfig/elasticsearch` missing. Was this while running the role or did you try to manually install the plugin. (The later one is not supported/recommended when using the role.)
* Can you apply the above plugin change to your playbook and see if that solves your issue?
* If it doesn't, try using the role from a tag instead of master. E.g.:
  * Go to the role folder, execute `git checkout tags/0.1.2 `

If it still fails, please run wit `-vvv`  and gist the output.

**Comment by GenmillsKM** [comment]
any update on this?

during my job run I get 
```
TASK [elasticsearch : Install elasticsearch plugins] ***************************
task path: /mnt/git_repos/ansible-elasticsearch/tasks/elasticsearch-plugins.yml:35
skipping: [esnode1] => (item={u'plugin': u'license'})  => {"changed": false, "item": {"plugin": "license"}, "skip_reason": "Conditional check failed", "skipped": true}
skipping: [esnode1] => (item={u'plugin': u'marvel'})  => {"changed": false, "item": {"plugin": "marvel"}, "skip_reason": "Conditional check failed", "skipped": true}
skipping: [esnode1] => (item={u'plugin': u'shield'})  => {"changed": false, "item": {"plugin": "shield"}, "skip_reason": "Conditional check failed", "skipped": true}
```


In my playbook I have the following vars:
### vars:
    es_templates: true
    es_version_lock: false
    es_heap_size: 8g
    es_major_varsion: "2.x"
    es_start_service: false
    es_api_port: 50000
    es_version: "2.4.1"
    es_plugins_reinstall: true
    es_plugins:
     - plugin: license
     - plugin: marvel
     - plugin: shield

**Comment by barryib** [comment]
@GenmillsKM (or @Thermi) can you please answer to @jakommo's questions above?

**Comment by Thermi** [comment]
> When you got the error about /etc/sysconfig/elasticsearch missing. Was this while running the role or did you try to manually install the plugin. (The later one is not supported/recommended when using the role.)
The latter. But the file is still included and there's no code in the plugin script that changes that file name in any way.

> Can you apply the above plugin change to your playbook and see if that solves your issue?
Yes, we solved the issue with the syntax above.

The problem was, that the example was wrong. Please provide valid and working ones, thanks.

**Comment by GenmillsKM** [comment]
hm. I've been using the syntax above in my vars: and those tasks are still skipped.

**Comment by veger** [comment]
There are some 'weird' (make no sense for ES 5.x, see below) filters in the commands that check which templates are installed:
* [elasticsearch-plugins.ym#L14](https://github.com/elastic/ansible-elasticsearch/blob/6470b01512fb4baed228d01268573ed73b5d48b0/tasks/elasticsearch-plugins.yml#L14)
* [elasticsearch-xpack-install.yml#L4](https://github.com/elastic/ansible-elasticsearch/blob/6470b01512fb4baed228d01268573ed73b5d48b0/tasks/xpack/elasticsearch-xpack-install.yml#L4)
* [elasticsearch-xpack.yml#L10](https://github.com/elastic/ansible-elasticsearch/blob/6470b01512fb4baed228d01268573ed73b5d48b0/tasks/xpack/elasticsearch-xpack.yml#L10)

In order to fix installing plugins (using the `elasticsearch-plugin` command) I removed them in PR #178

This is for ES 5.x, but maybe this was also an issue with ES 2.x? (I do not know, as I never used ES < 5.x, so I do not know the output of the `plugin` command)

**Comment by gingerwizard** [comment]
This should be resolved in current master.
