### ISSUE TITLE
Install ES with versions < 2.x

### ISSUE THREAD

**Issue by nsushain90** [elastic/ansible-elasticsearch#383]
Im trying to install Elasticsearch with version 1.7.6. Issue is there is no release file for 1.x .I don't see it working with branch 2.x either. How can I get this working ? is there a workaround.

**Comment by jakommo** [comment]
Hi @nsushain90, as noted in the [README](https://github.com/elastic/ansible-elasticsearch#ansible-elasticsearch) this role is from 2.x and 5.x only. 
Is there a reason for using 1.7? It's End of Life for quite some time now and does not receive any (security) updates anymore. 
Also, there are a lot of issues that have been fixed in 2.x/5.x and we are actually on our way to [release 6.0](https://www.elastic.co/blog/elasticsearch-6-0-0-rc1-released).
I'd highly recommend to go for 5.x if you are in the process of setting up a cluster. It doesn't make any sense to setup a new cluster with an outdated/EoL'd version. 
Closing as 1.7 is not supported by this role anymore.
