### ISSUE TITLE
Feature Request: ES 6.x support

### ISSUE THREAD

**Issue by tburow** [elastic/ansible-elasticsearch#407]
**Describe the feature**:
Request a new branch for ES 6.x support given current branch does not work with ES 6.x & pending PR changes may or may not impact ES 5.x.   request that a new branch be created with the pending ES6.x changes for the version upgrade.

**Comment by hokeycokey** [comment]
6.x branch would be handy indeed.

**Comment by doubledeee** [comment]
+1 for this request.

**Comment by drewr** [comment]
Quick status on this, we are working on fully supporting 6.0+, including evaluating the open PRs (#397, #405, #408), and otherwise working on. If anyone wants to work full-time on Ansible with an awesome Infra team, particularly if you're in EMEA or APJ timezones, let me know! 😄

**Comment by Crazybus** [comment]
Latest progress for 6.x support can be followed in https://github.com/elastic/ansible-elasticsearch/pull/412 which based on the work from https://github.com/elastic/ansible-elasticsearch/pull/408 . 

I'm currently fixing up the last of the tests so that all tests and platforms are passing for 5.x and 6.x which is now being automatically [tested via jenkins](https://devops-ci.elastic.co/job/elastic+ansible-elasticsearch+pull-request/) for each pull request

**Comment by Crazybus** [comment]
[6.1.3](https://github.com/elastic/ansible-elasticsearch/releases/tag/6.1.3) has been released!
