### ISSUE TITLE
[feature request] check compatible versions

### ISSUE THREAD

**Issue by abraxxa** [elastic/ansible-elasticsearch#419]
As ansible-elasticsearch 6.1.3 isn't compatible with 6.2.0 it breaks each node in the cluster because of the missing /etc/default/elasticsearch file on restart.
This gave me the idea to add a check as the first task of the playbook which validates the es_version variable and aborts if an unsupported version is requested.

**Comment by cl0udf0x** [comment]
Issue listed here too: #420

**Comment by abraxxa** [comment]
#420 is the issue I‘ve hit with 6.2 but this is a safeguard feature for the playbook generally before it is tested and adapted if required for a new Elasticsearch version.

**Comment by benrudolph** [comment]
Recently ran into this and it cause a lot of head banging. Think it's a great suggestion

**Comment by Crazybus** [comment]
Is there something preventing you from updating to the 6.2.X release of the ansible-playbook? Going forward we are going to be releasing this playbook with every minor version release of elasticsearch. 

There are quite a few challenges with adding a check for "compatible versions". Which makes me hesitant to try and solve this problem by creating a list of compatible versions. If anyone else has some great ideas of how to implement this I'm all ears! 

### Having a check to see if the es_version > the playbook version

I think this is the most sane option. Having a task which fails if you try to deploy elasticsearch `6.2.0` with the playbook version `6.1.3`. Then having another variable to allow you to disable this with a "This isn't supported but I know what I'm doing" option. 

The best approach is probably to make sure that the major version isn't greater. So `6.1.3` can probably deploy `6.1.4` but not `6.2.0`.

### Having a list of multiple supported versions

If we wanted to have a list of supported versions we would then need to run all of the testing against all of the supported versions. The [testing matrix](https://devops-ci.elastic.co/job/elastic+ansible-elasticsearch+pull-request/) currently has 56 combinations. Having even two supported versions would result in 112 testing combinations. So I don't think is a really great option. 

### Having a single es_version that can't be overridden

Moving `es_version` into the `vars/` directory so that it can't be overridden. Doing this would break the [version upgrade testing](https://github.com/elastic/ansible-elasticsearch/blob/master/test/integration/xpack.yml) we do and would mean that people can't upgrade minor release versions until a new playbook version has been deployed. 


> As ansible-elasticsearch 6.1.3 isn't compatible with 6.2.0 it breaks each node in the cluster because of the missing /etc/default/elasticsearch file on restart.

This happened in a testing/acceptance environment first right? I'm hoping you aren't deploying new versions of elasticsearch directly to a production cluster. If you don't currently have a testing environment you can also test using the kitchen environment from this repo.

You could first deploy your current version. 

`bundle exec kitchen converge standard-ubuntu-1604`
`bundle exec kitchen verify standard-ubuntu-1604`

Then upgrade the `es_version` to `6.2.0` and run it again.

`bundle exec kitchen converge standard-ubuntu-1604`
`bundle exec kitchen verify standard-ubuntu-1604`
