### ISSUE TITLE
es_custom_package_url is undocumented

### ISSUE THREAD

**Issue by dawi** [elastic/ansible-elasticsearch#496]
The variable `es_custom_package_url` is undocumented.  

**Is it safe to be used?**

**Comment by Crazybus** [comment]
> It would be nice to set es_use_repository automatically to false if someone want's to specify the exact package via url.

Agreed. It's silly to manually do it if it always needs to be done.

> Also it would be nice to determine the es_version from the package to install.

This one is a bit trickier since you can't expect the custom url to always have the version in it. And if it does it would be hard to determine which version like string it actually is. You might also have multiple version like numbers in the url like https://downloads.example.com/2018.11.01/6.4/6.4.0. 

To make your code more dry I would suggest doing something like:

```
es_version: 5.6.2
es_use_repository: false
es_custom_package_url: "https://.../elasticsearch-{{ es_version }}.deb"
```
