### ISSUE TITLE
elasticsearch.keystore

### ISSUE THREAD

**Issue by kakoni** [elastic/ansible-elasticsearch#518]
Elasticstore 6.x (atleast 6.5) rpm has postinstall script
```
if [ ! -f /etc/elasticsearch/elasticsearch.keystore ]; then
    /usr/share/elasticsearch/bin/elasticsearch-keystore create
    chown root:elasticsearch /etc/elasticsearch/elasticsearch.keystore
    chmod 660 /etc/elasticsearch/elasticsearch.keystore
    md5sum /etc/elasticsearch/elasticsearch.keystore > /etc/elasticsearch/.elasticsearch.keystore.initial_md5sum
fi
```

So keystore will be automatically created as this is a standard feature of elasticsearch, not just x-pack.
So would the wise strategy to be to delete this file and create new one under ES_PATH_CONF, regardless of x-pack security option?

**Comment by Crazybus** [comment]
> So would the wise strategy to be to delete this file

This would not be wise since we can't assume that this file isn't being used by a different cluster running on the same host. Deleting someones keystore doesn't sound like a good idea. 

> create new one under ES_PATH_CONF, regardless of x-pack security option?

This is already what happens. The rpm script creates it in the default location but Elasticsearch will also initialize one automatically in `ES_PATH_CONF` if it doesn't exist. The only thing that Ansible is doing is making sure that the file [permissions](https://github.com/elastic/ansible-elasticsearch/blob/5329dc71299f52a4567fc4f573cd196453406004/tasks/xpack/elasticsearch-xpack.yml#L19-L23) have been set correctly. If you run the default example you will see that a keystore exists as expected. 

Is the keystore missing for you or are you running into any other problems?

**Comment by kakoni** [comment]
> This would not be wise since we can't assume that this file isn't being used by a different cluster running on the same host. 

Ok, so one could proceed and delete this manually if only ansible is used to install elastic.

> Is the keystore missing for you or are you running into any other problems?

No its there alright. Just multiple elasticsearch.keystore:s causing confusion;) 

Ok, but I close this as this is the way it should work.
