### ISSUE TITLE
Documentation for enable auth

### ISSUE THREAD

**Issue by Oros42** [elastic/ansible-elasticsearch#662]
In the README.md, it's not explaine that to enable auth on the API, you need :  
- es_enable_xpack
- es_api_basic_auth_username
- es_api_basic_auth_password

So to enable auth on the API, you have to set this :  
```
es_enable_xpack: true
es_api_basic_auth_username: elastic
es_api_basic_auth_password: MyPassword
```
It will be nice to add this block in the README.md to save time of Adsys.
Thank you ;-)

**Comment by jmlrt** [comment]
Hi @Oros42, thank you for submitting this.

#653 should simplify that by removing the confusing `es_enable_xpack` variable.

**Comment by jmlrt** [comment]
Meanwhile it's worth to mention that `es_enable_xpack` variable default value is set to true so the only variables to really set are `es_api_basic_auth_username` and `es_api_basic_auth_password` which are documented [here](https://github.com/elastic/ansible-elasticsearch#important-note-for-native-realm-configuration).

**Comment by jmlrt** [comment]
In addition to the refactoring started in #653, it seems that we need to improve authentication documentation. We will use this issue to track it and expect to start it in a few weeks.

Quotes from #688:
>The fact that es_basic_auth_username and es_basic_user_password are needed for any security
related config to be written (see templates/elasticsearch.yml.j2) is not reflected in the documentation. Furthermore it is stated that these variables are soley needed for the configuration
of the native realm.

>Configuring security features but ommiting these variables, because the native realm is not used, leads to a silent fail of the parameter check mentioned above and subsequently all security
parameters are ommited in the actual configuration file on the node.

See also #650 for questions about authentications

**Comment by smutel** [comment]
Hello,

I would like to share my issue there because I think it's related to a documentation issue. If I should create a new issue, please tell me.

I would like to setup the authentication on elasticsearch. Regarding the last documentation, it's not needed to have a license to do this. I followed the documentation (https://github.com/elastic/ansible-elasticsearch/blob/master/docs/ssl-tls-setup.md) but setting `es_api_basic_auth_username` and `es_api_basic_auth_password` does not seem to be enough.

The account `es_api_basic_auth_username` will be created by the playbook ?  
Do I need to create it manually ?

**Comment by smutel** [comment]
https://github.com/elastic/ansible-elasticsearch/pull/728
