### ISSUE TITLE
Please standardize documentation convention

### ISSUE THREAD

**Issue by trondhindenes** [elastic/ansible-elasticsearch#713]
THe documentation mixes yaml conventions:

```
      es_config:
        cluster.name: "supercluster"
```

and 
```
      es_config['cluster.name']: "supercluster"
```
people unfamiliar with yaml/python will likely find this very confusing. Please stick to one convention for documenting settings

**Comment by jmlrt** [comment]
Hi @trondhindenes, thanks for submitting this request.

The "multiline yaml" for is used for the full configuration examples because it really reflects what you should have in your ansible variables, while the "single line yaml" is used for the description of each variables.

IMO, I consider yaml familiarity as a requirement to use Ansible in general, not only this specific role.

I don't see a good way to have these variables description using "multi line yaml" without loosing clarity.

Do you have any idea how we could do that? Can you submit some examples or maybe a PR?

**Comment by trondhindenes** [comment]
I would just use a comment block:
```yaml
es_config:
        cluster.name: "supercluster" #the name of the cluster
```

**Comment by jmlrt** [comment]
Make sense, can you submit a PR for that?
